### ISSUE TITLE
.isView() fails for falsy property values

### ISSUE THREAD

**Issue by mootari** [jonschlinkert/load-templates#4]
The .isView() implementation in this package does not use `.hasOwnProperty()` (as `templates` does). As a result `isView()` returns false if .e.g. `content` is set to an empty string:
https://github.com/jonschlinkert/load-templates/blob/995ccaf1955652ad3401d8457f331917b308b110/utils.js#L61-L70

As a side note, I've now seen three different implementations of `.isView()` (templates, load-templates, assemble-loader). Might be a good idea to consolidate them somehow?

**Comment by jonschlinkert** [comment]
> Might be a good idea to consolidate them somehow?

agreed. I thought we had an `is-view` implementation somewhere that we were going to use for this.
